spring.application.name=secure-online-examination-platform
server.port=8081
jwt.secret=ReplaceThisWithASecretKeyThatIsAtLeast32CharactersLong123456
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
